version: "3"
services:
  app:
    build:
      context: .
      args:
        PLANTUML_DIR: "/plantuml"
        FONT_DIR: "/font"
    volumes:
      - ./app/:/docs/source
      - ./build/:/docs/build
    ports:
      - 8888:8000
    environment:
      PLANTUML_DIR: "/plantuml"
      FONT_DIR: "/font"
      STATIC_DIR: "_static"
      TEMPLATE_DIR: "_templates"
