version: "3"
services:
  app:
    # https://github.com/hnakamur/docker-sphinx/tree/9a1504540cce85c8c4f1ae6003b56b82f5efac8a
    image: ${IMAGE_1}
    container_name: ${CONTAINER_NAME_1}
    environment:
      - USE_GOSU=1
      - LOCAL_UID=${UID}
      - LOCAL_GID=${GID}
    user: ${UID}:${GID}
    volumes:
      - ${WORKDIR_HOST_1}:${WORKDIR_DOCKER_1}
      - ${SCRIPTDIR_HOST_1}:${SCRIPTDIR_DOCKER_1}
    working_dir: ${WORKDIR_DOCKER_1}
    ports:
      - ${PORT_HOST_1}:${PORT_DOCKER_1}
    command: ${COMMAND_1}
