version: "3"
services:
  app:
    build:
      context: .
      args:
        PLANTUML_DIR: "/plantuml"
        FONT_DIR: "/font"
    volumes:
      - ./app:/app
    ports:
      - 8888:8000
    environment:
      # used at conf.py
      STATIC_DIR: "_static"
      TEMPLATE_DIR: "_templates"
    # build html or pdf
    command: ["sphinx-autobuild", ".", "_build/html", "--host", "0.0.0.0"]
    #command: ["make", "latexpdfja"]